### ISSUE TITLE
Dependencies and types

### ISSUE THREAD

**Issue by MMT-LD** [paulbuechner/storybook-addon-data-theme-switcher#10]
Hey!

Great job! I was just going to write my own then i discovered yours.

The only thing that would be a nice to have is to fix the peer dependencies warning for later versions of storybook or relax them a little. PNPM notifies that the additional peers need to be installed. But the latest storybook is 7.0.4 for example. Maybe use 7.0.x as the version to relax it a little.

![Screenshot 2023-04-13 at 16 55 04](https://user-images.githubusercontent.com/28092872/231891678-2bb8fe20-288c-47e5-94ad-510068f8020b.png)

Also the types are not exposed for using outside of the package.

Thanks!

**Comment by paulbuechner** [comment]
Hey! I fixed the types issue as they weren't exposed in the `package.json` -> `exports` configuration.

The warning is OK. You can get rid of the warning by either manually installing the missing dependencies to your project or configuring your package manager to install missing peers automatically. As of `pnpm` version 8 this feature is enabled by default. Otherwise, see [here](https://pnpm.io/next/npmrc#auto-install-peers).
